name: Tests

on: push

jobs:
  build:
    name: ${{ matrix.os }} / ${{ matrix.python }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
        - ubuntu-latest
        python:
        - '3.7'
        - '3.8'
        - '3.9'
        - '3.10'
        - '3.11'
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python }}
    - run: make init
    - run: make pr

env:
  PIP_INDEX_URL: https://pypi-wayback-449168051873.europe-west3.run.app/2023-10-31
  UV_INDEX_URL: https://pypi-wayback-449168051873.europe-west3.run.app/2023-10-31
